# Breast Cancer Wisconsin (Diagnostic) 


In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [2]:
dataset = pd.read_csv('wdbc.data', header=None)

In [3]:
print(dataset.shape)
dataset.head()


(569, 32)


0  1      2      3       4       5        6        7       8   \
0    842302  M  17.99  10.38  122.80  1001.0  0.11840  0.27760  0.3001   
1    842517  M  20.57  17.77  132.90  1326.0  0.08474  0.07864  0.0869   
2  84300903  M  19.69  21.25  130.00  1203.0  0.10960  0.15990  0.1974   
3  84348301  M  11.42  20.38   77.58   386.1  0.14250  0.28390  0.2414   
4  84358402  M  20.29  14.34  135.10  1297.0  0.10030  0.13280  0.1980   

        9   ...     22     23      24      25      26      27      28      29  \
0  0.14710  ...  25.38  17.33  184.60  2019.0  0.1622  0.6656  0.7119  0.2654   
1  0.07017  ...  24.99  23.41  158.80  1956.0  0.1238  0.1866  0.2416  0.1860   
2  0.12790  ...  23.57  25.53  152.50  1709.0  0.1444  0.4245  0.4504  0.2430   
3  0.10520  ...  14.91  26.50   98.87   567.7  0.2098  0.8663  0.6869  0.2575   
4  0.10430  ...  22.54  16.67  152.20  1575.0  0.1374  0.2050  0.4000  0.1625   

       30       31  
0  0.4601  0.11890  
1  0.2750  0.08902  
2  0.3613  0.08758  
3  0.6638  0.17300  
4  0.2364  0.07678  

[5 rows x 32 columns]

**Remoção do id**: essa informação não acrescenta em nada para a tarefa de classificação que desejamos


In [4]:
dataset.drop(labels=dataset.columns[0], axis=1, inplace=True)
dataset.head()

1      2      3       4       5        6        7       8        9       10  \
0  M  17.99  10.38  122.80  1001.0  0.11840  0.27760  0.3001  0.14710  0.2419   
1  M  20.57  17.77  132.90  1326.0  0.08474  0.07864  0.0869  0.07017  0.1812   
2  M  19.69  21.25  130.00  1203.0  0.10960  0.15990  0.1974  0.12790  0.2069   
3  M  11.42  20.38   77.58   386.1  0.14250  0.28390  0.2414  0.10520  0.2597   
4  M  20.29  14.34  135.10  1297.0  0.10030  0.13280  0.1980  0.10430  0.1809   

   ...     22     23      24      25      26      27      28      29      30  \
0  ...  25.38  17.33  184.60  2019.0  0.1622  0.6656  0.7119  0.2654  0.4601   
1  ...  24.99  23.41  158.80  1956.0  0.1238  0.1866  0.2416  0.1860  0.2750   
2  ...  23.57  25.53  152.50  1709.0  0.1444  0.4245  0.4504  0.2430  0.3613   
3  ...  14.91  26.50   98.87   567.7  0.2098  0.8663  0.6869  0.2575  0.6638   
4  ...  22.54  16.67  152.20  1575.0  0.1374  0.2050  0.4000  0.1625  0.2364   

        31  
0  0.11890  
1  0.08902  
2  0.08758  
3  0.17300  
4  0.07678  

[5 rows x 31 columns]

In [5]:
dataset.isna().sum()

1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
30    0
31    0
dtype: int64

 Forma de ver toda a informação no notebook

In [6]:
pd.options.display.max_columns = None
dataset.describe()


2           3           4            5           6   \
count  569.000000  569.000000  569.000000   569.000000  569.000000   
mean    14.127292   19.289649   91.969033   654.889104    0.096360   
std      3.524049    4.301036   24.298981   351.914129    0.014064   
min      6.981000    9.710000   43.790000   143.500000    0.052630   
25%     11.700000   16.170000   75.170000   420.300000    0.086370   
50%     13.370000   18.840000   86.240000   551.100000    0.095870   
75%     15.780000   21.800000  104.100000   782.700000    0.105300   
max     28.110000   39.280000  188.500000  2501.000000    0.163400   

               7           8           9           10          11          12  \
count  569.000000  569.000000  569.000000  569.000000  569.000000  569.000000   
mean     0.104341    0.088799    0.048919    0.181162    0.062798    0.405172   
std      0.052813    0.079720    0.038803    0.027414    0.007060    0.277313   
min      0.019380    0.000000    0.000000    0.106000    0.049960    0.111500   
25%      0.064920    0.029560    0.020310    0.161900    0.057700    0.232400   
50%      0.092630    0.061540    0.033500    0.179200    0.061540    0.324200   
75%      0.130400    0.130700    0.074000    0.195700    0.066120    0.478900   
max      0.345400    0.426800    0.201200    0.304000    0.097440    2.873000   

               13          14          15          16          17          18  \
count  569.000000  569.000000  569.000000  569.000000  569.000000  569.000000   
mean     1.216853    2.866059   40.337079    0.007041    0.025478    0.031894   
std      0.551648    2.021855   45.491006    0.003003    0.017908    0.030186   
min      0.360200    0.757000    6.802000    0.001713    0.002252    0.000000   
25%      0.833900    1.606000   17.850000    0.005169    0.013080    0.015090   
50%      1.108000    2.287000   24.530000    0.006380    0.020450    0.025890   
75%      1.474000    3.357000   45.190000    0.008146    0.032450    0.042050   
max      4.885000   21.980000  542.200000    0.031130    0.135400    0.396000   

               19          20          21          22          23          24  \
count  569.000000  569.000000  569.000000  569.000000  569.000000  569.000000   
mean     0.011796    0.020542    0.003795   16.269190   25.677223  107.261213   
std      0.006170    0.008266    0.002646    4.833242    6.146258   33.602542   
min      0.000000    0.007882    0.000895    7.930000   12.020000   50.410000   
25%      0.007638    0.015160    0.002248   13.010000   21.080000   84.110000   
50%      0.010930    0.018730    0.003187   14.970000   25.410000   97.660000   
75%      0.014710    0.023480    0.004558   18.790000   29.720000  125.400000   
max      0.052790    0.078950    0.029840   36.040000   49.540000  251.200000   

                25          26          27          28          29  \
count   569.000000  569.000000  569.000000  569.000000  569.000000   
mean    880.583128    0.132369    0.254265    0.272188    0.114606   
std     569.356993    0.022832    0.157336    0.208624    0.065732   
min     185.200000    0.071170    0.027290    0.000000    0.000000   
25%     515.300000    0.116600    0.147200    0.114500    0.064930   
50%     686.500000    0.131300    0.211900    0.226700    0.099930   
75%    1084.000000    0.146000    0.339100    0.382900    0.161400   
max    4254.000000    0.222600    1.058000    1.252000    0.291000   

               30          31  
count  569.000000  569.000000  
mean     0.290076    0.083946  
std      0.061867    0.018061  
min      0.156500    0.055040  
25%      0.250400    0.071460  
50%      0.282200    0.080040  
75%      0.317900    0.092080  
max      0.663800    0.207500

## Divisão dos dados


In [7]:
X = pd.DataFrame(dataset.iloc[:,1:])
Y = pd.DataFrame(dataset.iloc[:, 0])

encoder_y = LabelEncoder() 
Y = pd.DataFrame( encoder_y.fit_transform(Y))

print(X.shape, Y.shape)

(569, 30) (569, 1)


C:\Users\igor.lucena\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [8]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)

In [9]:
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(455, 30) (455, 1)
(114, 30) (114, 1)


In [10]:
y_train.head()

0
565  1
483  0
334  0
295  0
231  0

## PCA


In [11]:
from sklearn.decomposition import PCA

In [12]:
pca = PCA(10)

In [13]:
pca.fit(x_train)

PCA(copy=True, iterated_power='auto', n_components=10, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [14]:
pca.explained_variance_ratio_.round(3)

array([0.982, 0.016, 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   ])

In [15]:
x_pca = pd.DataFrame( pca.transform(x_train))


In [16]:
x_pca.head()

0          1          2         3          4         5         6  \
0  1044.795594  74.153209  -4.498413 -6.242134  11.524042 -0.103784  0.456478   
1  -210.874095  29.438709  -8.853177  2.358524  -0.474448 -1.341640  0.625781   
2  -388.540411  12.265857  -5.160518  0.203049   5.328954 -0.057289  2.038942   
3  -226.726081  52.609482 -11.171974  8.946074  -4.526435 -0.877689  0.391293   
4  -503.148279   1.396506  -3.069070 -7.055307  11.206256  0.245271 -1.805152   

          7         8         9  
0  0.696542 -0.346786  0.460849  
1 -0.309513 -0.115074 -0.029484  
2 -0.031480 -0.149877  0.073989  
3 -0.232712 -0.087512  0.008695  
4 -1.044066  0.152927 -0.202089

## Feature Scaling
Pré-processamento dos dados


In [17]:

from sklearn.preprocessing import StandardScaler, Normalizer, MaxAbsScaler, MinMaxScaler, RobustScaler
scaler = StandardScaler()# alterar

x_train_norm =  pd.DataFrame(scaler.fit_transform(x_train)) 
x_train_norm.describe().round(3)

0        1        2        3        4        5        6        7   \
count  455.000  455.000  455.000  455.000  455.000  455.000  455.000  455.000   
mean     0.000    0.000    0.000   -0.000   -0.000    0.000   -0.000    0.000   
std      1.001    1.001    1.001    1.001    1.001    1.001    1.001    1.001   
min     -2.032   -1.974   -1.993   -1.461   -3.114   -1.660   -1.141   -1.294   
25%     -0.699   -0.714   -0.709   -0.679   -0.695   -0.752   -0.753   -0.746   
50%     -0.197   -0.120   -0.207   -0.286   -0.045   -0.228   -0.319   -0.395   
75%      0.522    0.555    0.522    0.397    0.618    0.535    0.545    0.695   
max      3.979    4.597    4.002    5.270    4.764    3.623    4.392    4.078   

            8        9        10       11       12       13       14       15  \
count  455.000  455.000  455.000  455.000  455.000  455.000  455.000  455.000   
mean     0.000   -0.000    0.000   -0.000   -0.000    0.000   -0.000   -0.000   
std      1.001    1.001    1.001    1.001    1.001    1.001    1.001    1.001   
min     -2.751   -1.763   -1.059   -1.552   -1.038   -0.720   -1.723   -1.287   
25%     -0.714   -0.704   -0.620   -0.669   -0.617   -0.486   -0.606   -0.697   
50%     -0.063   -0.174   -0.277   -0.213   -0.266   -0.337   -0.248   -0.283   
75%      0.533    0.452    0.267    0.441    0.265    0.114    0.395    0.385   
max      4.450    4.831    8.800    6.531    9.407   10.605    7.635    6.075   

            16       17       18       19       20       21       22       23  \
count  455.000  455.000  455.000  455.000  455.000  455.000  455.000  455.000   
mean     0.000   -0.000   -0.000    0.000    0.000    0.000   -0.000    0.000   
std      1.001    1.001    1.001    1.001    1.001    1.001    1.001    1.001   
min     -1.101   -1.914   -1.584   -1.062   -1.731   -2.160   -1.701   -1.234   
25%     -0.574   -0.626   -0.675   -0.568   -0.683   -0.727   -0.703   -0.652   
50%     -0.190   -0.132   -0.210   -0.212   -0.266   -0.059   -0.265   -0.341   
75%      0.371    0.455    0.374    0.272    0.547    0.661    0.581    0.386   
max     12.638    6.612    5.073    9.479    4.110    3.849    4.321    5.985   

            24       25       26       27       28       29  
count  455.000  455.000  455.000  455.000  455.000  455.000  
mean     0.000   -0.000    0.000   -0.000   -0.000   -0.000  
std      1.001    1.001    1.001    1.001    1.001    1.001  
min     -2.664   -1.412   -1.320   -1.749   -2.141   -1.548  
25%     -0.688   -0.670   -0.756   -0.757   -0.638   -0.686  
50%     -0.054   -0.268   -0.205   -0.225   -0.119   -0.237  
75%      0.590    0.507    0.531    0.714    0.438    0.429  
max      3.920    5.040    4.396    2.727    5.985    6.728

## Treinamento

In [18]:
# metricas
from sklearn.metrics import f1_score, accuracy_score, precision_score, recall_score, confusion_matrix

In [19]:
from sklearn.svm import SVC

In [20]:
clf = SVC(C=10) 
clf.fit(x_train_norm, y_train)

pred = clf.predict(x_train_norm)
print('accuracy', accuracy_score(y_train,pred))
print('precision', precision_score(y_train,pred,average='micro' ))
print('recall', recall_score(y_train,pred, average='micro'))
print('f1', f1_score(y_train,pred,average='micro'))
confusion_matrix(y_train,pred)

accuracy 0.9934065934065934
precision 0.9934065934065934
recall 0.9934065934065934
f1 0.9934065934065934


C:\Users\igor.lucena\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[283,   0],
       [  3, 169]], dtype=int64)

## Test

In [21]:
#x_test_pca = pca.transform(x_test)
x_test_norm = scaler.transform(x_test)

In [22]:
pred = clf.predict(x_test_norm)
print('accuracy', accuracy_score(y_test,pred))
print('precision', precision_score(y_test,pred,average='micro' ))
print('recall', recall_score(y_test,pred, average='micro'))
print('f1', f1_score(y_test,pred,average='micro'))
confusion_matrix(y_test,pred)

accuracy 0.9736842105263158
precision 0.9736842105263158
recall 0.9736842105263158
f1 0.9736842105263158


array([[73,  1],
       [ 2, 38]], dtype=int64)