# Breast Cancer Wisconsin (Diagnostic) 


In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [2]:
dataset = pd.read_csv('wdbc.data', header=None)

In [3]:
print(dataset.shape)
dataset.head()


(569, 32)


0  1      2      3       4       5        6        7       8   \
0    842302  M  17.99  10.38  122.80  1001.0  0.11840  0.27760  0.3001   
1    842517  M  20.57  17.77  132.90  1326.0  0.08474  0.07864  0.0869   
2  84300903  M  19.69  21.25  130.00  1203.0  0.10960  0.15990  0.1974   
3  84348301  M  11.42  20.38   77.58   386.1  0.14250  0.28390  0.2414   
4  84358402  M  20.29  14.34  135.10  1297.0  0.10030  0.13280  0.1980   

        9    ...        22     23      24      25      26      27      28  \
0  0.14710   ...     25.38  17.33  184.60  2019.0  0.1622  0.6656  0.7119   
1  0.07017   ...     24.99  23.41  158.80  1956.0  0.1238  0.1866  0.2416   
2  0.12790   ...     23.57  25.53  152.50  1709.0  0.1444  0.4245  0.4504   
3  0.10520   ...     14.91  26.50   98.87   567.7  0.2098  0.8663  0.6869   
4  0.10430   ...     22.54  16.67  152.20  1575.0  0.1374  0.2050  0.4000   

       29      30       31  
0  0.2654  0.4601  0.11890  
1  0.1860  0.2750  0.08902  
2  0.2430  0.3613  0.08758  
3  0.2575  0.6638  0.17300  
4  0.1625  0.2364  0.07678  

[5 rows x 32 columns]

**Remoção do id**: essa informação não acrescenta em nada para a tarefa de classificação que desejamos


In [4]:
dataset.drop(labels=dataset.columns[0], axis=1, inplace=True)
dataset.head()

1      2      3       4       5        6        7       8        9       10  \
0  M  17.99  10.38  122.80  1001.0  0.11840  0.27760  0.3001  0.14710  0.2419   
1  M  20.57  17.77  132.90  1326.0  0.08474  0.07864  0.0869  0.07017  0.1812   
2  M  19.69  21.25  130.00  1203.0  0.10960  0.15990  0.1974  0.12790  0.2069   
3  M  11.42  20.38   77.58   386.1  0.14250  0.28390  0.2414  0.10520  0.2597   
4  M  20.29  14.34  135.10  1297.0  0.10030  0.13280  0.1980  0.10430  0.1809   

    ...        22     23      24      25      26      27      28      29  \
0   ...     25.38  17.33  184.60  2019.0  0.1622  0.6656  0.7119  0.2654   
1   ...     24.99  23.41  158.80  1956.0  0.1238  0.1866  0.2416  0.1860   
2   ...     23.57  25.53  152.50  1709.0  0.1444  0.4245  0.4504  0.2430   
3   ...     14.91  26.50   98.87   567.7  0.2098  0.8663  0.6869  0.2575   
4   ...     22.54  16.67  152.20  1575.0  0.1374  0.2050  0.4000  0.1625   

       30       31  
0  0.4601  0.11890  
1  0.2750  0.08902  
2  0.3613  0.08758  
3  0.6638  0.17300  
4  0.2364  0.07678  

[5 rows x 31 columns]

In [5]:
dataset.isna().sum()

1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
30    0
31    0
dtype: int64

 Forma de ver toda a informação no notebook

In [6]:
pd.options.display.max_columns = None
dataset.describe()


2           3           4            5           6   \
count  569.000000  569.000000  569.000000   569.000000  569.000000   
mean    14.127292   19.289649   91.969033   654.889104    0.096360   
std      3.524049    4.301036   24.298981   351.914129    0.014064   
min      6.981000    9.710000   43.790000   143.500000    0.052630   
25%     11.700000   16.170000   75.170000   420.300000    0.086370   
50%     13.370000   18.840000   86.240000   551.100000    0.095870   
75%     15.780000   21.800000  104.100000   782.700000    0.105300   
max     28.110000   39.280000  188.500000  2501.000000    0.163400   

               7           8           9           10          11          12  \
count  569.000000  569.000000  569.000000  569.000000  569.000000  569.000000   
mean     0.104341    0.088799    0.048919    0.181162    0.062798    0.405172   
std      0.052813    0.079720    0.038803    0.027414    0.007060    0.277313   
min      0.019380    0.000000    0.000000    0.106000    0.049960    0.111500   
25%      0.064920    0.029560    0.020310    0.161900    0.057700    0.232400   
50%      0.092630    0.061540    0.033500    0.179200    0.061540    0.324200   
75%      0.130400    0.130700    0.074000    0.195700    0.066120    0.478900   
max      0.345400    0.426800    0.201200    0.304000    0.097440    2.873000   

               13          14          15          16          17          18  \
count  569.000000  569.000000  569.000000  569.000000  569.000000  569.000000   
mean     1.216853    2.866059   40.337079    0.007041    0.025478    0.031894   
std      0.551648    2.021855   45.491006    0.003003    0.017908    0.030186   
min      0.360200    0.757000    6.802000    0.001713    0.002252    0.000000   
25%      0.833900    1.606000   17.850000    0.005169    0.013080    0.015090   
50%      1.108000    2.287000   24.530000    0.006380    0.020450    0.025890   
75%      1.474000    3.357000   45.190000    0.008146    0.032450    0.042050   
max      4.885000   21.980000  542.200000    0.031130    0.135400    0.396000   

               19          20          21          22          23          24  \
count  569.000000  569.000000  569.000000  569.000000  569.000000  569.000000   
mean     0.011796    0.020542    0.003795   16.269190   25.677223  107.261213   
std      0.006170    0.008266    0.002646    4.833242    6.146258   33.602542   
min      0.000000    0.007882    0.000895    7.930000   12.020000   50.410000   
25%      0.007638    0.015160    0.002248   13.010000   21.080000   84.110000   
50%      0.010930    0.018730    0.003187   14.970000   25.410000   97.660000   
75%      0.014710    0.023480    0.004558   18.790000   29.720000  125.400000   
max      0.052790    0.078950    0.029840   36.040000   49.540000  251.200000   

                25          26          27          28          29  \
count   569.000000  569.000000  569.000000  569.000000  569.000000   
mean    880.583128    0.132369    0.254265    0.272188    0.114606   
std     569.356993    0.022832    0.157336    0.208624    0.065732   
min     185.200000    0.071170    0.027290    0.000000    0.000000   
25%     515.300000    0.116600    0.147200    0.114500    0.064930   
50%     686.500000    0.131300    0.211900    0.226700    0.099930   
75%    1084.000000    0.146000    0.339100    0.382900    0.161400   
max    4254.000000    0.222600    1.058000    1.252000    0.291000   

               30          31  
count  569.000000  569.000000  
mean     0.290076    0.083946  
std      0.061867    0.018061  
min      0.156500    0.055040  
25%      0.250400    0.071460  
50%      0.282200    0.080040  
75%      0.317900    0.092080  
max      0.663800    0.207500

## Divisão dos dados


In [7]:
X = pd.DataFrame(dataset.iloc[:,1:])
Y = pd.DataFrame(dataset.iloc[:, 0])

encoder_y = LabelEncoder() 
Y = pd.DataFrame( encoder_y.fit_transform(Y))

print(X.shape, Y.shape)

(569, 30) (569, 1)


C:\Users\igorl\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [8]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)

In [9]:
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(455, 30) (455, 1)
(114, 30) (114, 1)


In [10]:
y_train.head()

0
442  0
241  0
369  1
40   1
344  0

## PCA


In [11]:
from sklearn.decomposition import PCA

In [35]:
pca = PCA(5)

In [36]:
pca.fit(x_train)

PCA(copy=True, iterated_power='auto', n_components=5, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [37]:
pca.explained_variance_ratio_.round(3)

array([0.982, 0.016, 0.002, 0.   , 0.   ])

In [38]:
x_pca = pd.DataFrame( pca.transform(x_train))


In [39]:
x_pca.head()

0          1          2         3         4
0  -181.202773  29.846687  -1.316665 -5.468113  5.138933
1  -379.022563  20.877437  -9.442986 -7.814927 -0.864801
2  1590.022304   4.003042  -3.273461  2.793349  8.872917
3  -124.195567 -32.603430 -12.440097  3.931041 -3.107431
4  -430.350950 -12.620817   9.535743 -5.215638  3.842532

## Feature Scaling
Pré-processamento dos dados


In [40]:

from sklearn.preprocessing import StandardScaler, Normalizer, MaxAbsScaler, MinMaxScaler, RobustScaler
scaler = StandardScaler()# alterar

x_train_norm =  pd.DataFrame(scaler.fit_transform(x_pca)) 
x_train_norm.describe().round(3)

0        1        2        3        4
count  455.000  455.000  455.000  455.000  455.000
mean     0.000   -0.000   -0.000    0.000   -0.000
std      1.001    1.001    1.001    1.001    1.001
min     -1.267   -7.806   -2.217   -3.262   -3.145
25%     -0.645   -0.360   -0.427   -0.651   -0.550
50%     -0.329    0.002   -0.042   -0.111    0.022
75%      0.288    0.350    0.328    0.546    0.600
max      5.706    8.504   11.923    3.686    5.550

## Treinamento

In [41]:
# metricas
from sklearn.metrics import f1_score, accuracy_score, precision_score, recall_score, confusion_matrix

In [42]:
from sklearn.svm import SVC

In [43]:
clf = SVC(C=1) 
clf.fit(x_train_norm, y_train)

pred = clf.predict(x_train_norm)
print('accuracy', accuracy_score(y_train,pred))
print('precision', precision_score(y_train,pred ))
print('recall', recall_score(y_train,pred))
print('f1', f1_score(y_train,pred))
confusion_matrix(y_train,pred)

accuracy 0.9604395604395605
precision 0.9805194805194806
recall 0.9096385542168675
f1 0.9437500000000001


C:\Users\igorl\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[286,   3],
       [ 15, 151]], dtype=int64)

## Test

In [44]:
x_test_pca = pca.transform(x_test)
x_test_norm = scaler.transform(x_test_pca)

In [45]:
pred = clf.predict(x_test_norm)
print('accuracy', accuracy_score(y_test,pred))
print('precision', precision_score(y_test,pred ))
print('recall', recall_score(y_test,pred))
print('f1', f1_score(y_test,pred))
confusion_matrix(y_test,pred)

accuracy 0.9649122807017544
precision 0.9772727272727273
recall 0.9347826086956522
f1 0.9555555555555557


array([[67,  1],
       [ 3, 43]], dtype=int64)

steps = [ ('RF', RandomForestClassifier())]
param_grid = {'RF__n_estimators': [5, 10, 15], 'RF__criterion':['gini', 'entropy'], 'RF__max_depth':[5,8]}

estimator = Pipeline(steps=steps)
cv_rf = GridSearchCV(estimator, param_grid, verbose=5, n_jobs=-1, cv=10)
cv_rf.fit(x_norm, y)
